/** Writer機能テストの全スイートを登録する集約エントリ。 */
import './writer-features/storage-location.test.mjs'
import './writer-features/recovery.test.mjs'
import './writer-features/document-session.test.mjs'
import './writer-features/search.test.mjs'
import './writer-features/statistics.test.mjs'
import './writer-features/main-window.test.mjs'
import './writer-features/project-tree-window.test.mjs'
import './writer-features/project-tree-interaction.test.mjs'
import './writer-features/preferences.test.mjs'
import './writer-features/settings-controller.test.mjs'
import './writer-features/toolbar.test.mjs'
